// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuHq7hbKCxj1W6jC8cvbTIJyS0xuQ4eDs',
    appId: '1:777298785218:web:bf489cb69d5c96574e5c5b',
    messagingSenderId: '777298785218',
    projectId: 'heydude-3073f',
    authDomain: 'heydude-3073f.firebaseapp.com',
    storageBucket: 'heydude-3073f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD859QA7x14c04ieo6M8ZQ8n1vU_goipc4',
    appId: '1:777298785218:android:9a898ed88f1c5e2b4e5c5b',
    messagingSenderId: '777298785218',
    projectId: 'heydude-3073f',
    storageBucket: 'heydude-3073f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD3A1bnW4fyBnZTpcXVK9x2J-Xc-iFTf8',
    appId: '1:777298785218:ios:2bb8af27b63824594e5c5b',
    messagingSenderId: '777298785218',
    projectId: 'heydude-3073f',
    storageBucket: 'heydude-3073f.appspot.com',
    iosBundleId: 'com.example.katiMasterclassApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD3A1bnW4fyBnZTpcXVK9x2J-Xc-iFTf8',
    appId: '1:777298785218:ios:2bb8af27b63824594e5c5b',
    messagingSenderId: '777298785218',
    projectId: 'heydude-3073f',
    storageBucket: 'heydude-3073f.appspot.com',
    iosBundleId: 'com.example.katiMasterclassApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuHq7hbKCxj1W6jC8cvbTIJyS0xuQ4eDs',
    appId: '1:777298785218:web:b23ab67276346a7a4e5c5b',
    messagingSenderId: '777298785218',
    projectId: 'heydude-3073f',
    authDomain: 'heydude-3073f.firebaseapp.com',
    storageBucket: 'heydude-3073f.appspot.com',
  );

}